---
- hosts: all
  roles:
    - common
  vars:
    go_user: "{{ terrauser }}"
  tags:
    - common

- hosts: terranodes
  roles:
  - role: terranode
    action: chaindata 
    tags: 
      - get-chain-data
  - role: terranode
    action: terranode
    tags: 
      - node  
     
# sentry support tbd
#- hosts: sentries
#  roles:
#    - role: sentry
#      action: sentry
#      tags: 
#        - sentry

- hosts: validator
  roles:
    - role: terranode
      action: lcd
      tags: 
        - lcd 
    - role: terranode
      action: validator 
      tags: 
        - validator 

- hosts: oracle
  roles:
    - role: oracle
      action: price-server
      tags: 
        - price-server
    - role: oracle
      action: feeder
      tags: 
        - feeder 


